services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=admin123
    depends_on:
      - db

  db:
    image: postgres:16.10-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: admin123

volumes:
  pgdata: